Enable backward compatibility in Bitcoin Core v0.16
I also tested this successfully in v0.15.1 and v0.13.2.

Without this flag to bitcoind, create-deposit-data fails like so:

error code: -5
error message:
Invalid public key: mn1f471kQHYx9oUnwc4TUy9KzbMx9847Dk
Note that from v0.16, createmultisig no longer accepts addresses. Clients must transition to using addmultisigaddress to create multisig addresses with addresses known to the wallet before upgrading to v0.17. To use the deprecated functionality, start bitcoind with -deprecatedrpc=createmultisig
Traceback (most recent call last):
  File "./glacierscript.py", line 796, in <module>
      deposit_interactive(args.m, args.n, args.dice, args.rng)
        File "./glacierscript.py", line 595, in deposit_interactive
	    "bitcoin-cli -testnet -datadir=bitcoin-test-data createmultisig {0}".format(argstring), shell=True)
	      File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
	          raise CalledProcessError(retcode, cmd, output=output)
		  subprocess.CalledProcessError: Command 'bitcoin-cli -testnet -datadir=bitcoin-test-data createmultisig 2 '["mn1f471kQHYx9oUnwc4TUy9KzbMx9847Dk", "mxtjsVSypDUjWAvc5nNRMEqYY5C4G2HpWL", "mwLScBiargpRuEJJo9zkrCrcHkb23qJp4m", "muYPF5rfGfqM1ucX5BCcYpRLx1y2BJmYbC"]'' returned non-zero exit status 5